### PR TITLE
Adding simple function for opencpu testing purpose

### PR DESCRIPTION
**Pull request by fabianmoronzirfas**
This PR adds my simple function again to be able to test the opencpu container.

- adds R/simple.R
- adds man/simple.Rd
- adds simple function into NAMESPACE 
- adds myself to DESCRIPTION because… :-)

---
This change is [Reviewable](https://reviewable.io/reviews/kwb-r/fhpredict/3)

### CODE REVIEW

**Comment by mrustl** [comment]
___
*[DESCRIPTION, line 21 at r1](https://reviewable.io/reviews/kwb-r/fhpredict/3#-LZJVAW70zPEnH5FX4zd:-LZJVAW70zPEnH5FX4ze:b-8siv9u) ([raw file](https://github.com/kwb-r/fhpredict/blob/161b0d9e5656c09bc444f00abf92220dbd67b47f/DESCRIPTION#L21)):*
> ```
>              comment = c(ORCID = "0000-0003-0647-7726")),
>       person(given = "Fabian",
>              family = "Morón Zirfas",
> ```

Could you please replace the "ó" with its unicode encoding "\u00F3"?

**Comment by mrustl** [comment]
___
*[DESCRIPTION, line 46 at r1](https://reviewable.io/reviews/kwb-r/fhpredict/3#-LZJW4kCEKmPTgd8ra9P:-LZJW4kCEKmPTgd8ra9Q:b-x39402) ([raw file](https://github.com/kwb-r/fhpredict/blob/161b0d9e5656c09bc444f00abf92220dbd67b47f/DESCRIPTION#L46)):*
> ```
> Encoding: UTF-8
> LazyData: true
> RoxygenNote: 6.1.1.9000
> ```

Please do not use the development version from GitHub and replace with its CRAN version (currently: 6.1.1 to my knowledge)

**Comment by mrustl** [comment]
___
*[man/simple.Rd, line 18 at r1](https://reviewable.io/reviews/kwb-r/fhpredict/3#-LZJWlln7IWA8-iZwopZ:-LZJWlln7IWA8-iZwop_:boybyht) ([raw file](https://github.com/kwb-r/fhpredict/blob/161b0d9e5656c09bc444f00abf92220dbd67b47f/man/simple.Rd#L18)):*
> ```
> \dontrun{simple()}
> }
> \keyword{simple}
> ```

Please roxygenise again after using the latest CRAN version of "roxygen2"

**Comment by mrustl** [comment]
___
*[DESCRIPTION, line 21 at r1](https://reviewable.io/reviews/kwb-r/fhpredict/3#-LZJVAW70zPEnH5FX4zd:-LZJcKiw3qI17mITMnY_:bb6ywmx) ([raw file](https://github.com/kwb-r/fhpredict/blob/161b0d9e5656c09bc444f00abf92220dbd67b47f/DESCRIPTION#L21)):*
<details><summary><i>Previously, fabianmoronzirfas (Fabian Morón Zirfas) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

**Comment by mrustl** [comment]
___
*[DESCRIPTION, line 46 at r1](https://reviewable.io/reviews/kwb-r/fhpredict/3#-LZJW4kCEKmPTgd8ra9P:-LZJcghOBrrFbFSE_kz0:bb6ywmx) ([raw file](https://github.com/kwb-r/fhpredict/blob/161b0d9e5656c09bc444f00abf92220dbd67b47f/DESCRIPTION#L46)):*
<details><summary><i>Previously, fabianmoronzirfas (Fabian Morón Zirfas) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

**Comment by mrustl** [comment]
*[a discussion](https://reviewable.io/reviews/kwb-r/fhpredict/3#-LZJcxTG2VKNN6ncQB_g:-LZJcxTG2VKNN6ncQB_h:bwzohp7) (no related file):*
Thanks for your contribution (and implementing my suggestions). :lgtm_strong:  but I think @hsonne should do the merge (as he is the package maintainer).

---

**Comment by hsonne** [comment]
Hi @fabianmoronzirfas and @mrustl, this looks all good to me.

**Comment by mrustl** [comment]
Looks Good To Me (LGTM).... was also a little lost with our reviewable.io commenting system.

**Comment by hsonne** [comment]
What you say is what I do!

**Pull request merged**
